import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
class Element{constructor(){this.value='';this.children=[];this.listeners={};}addEventListener(name,fn){this.listeners[name]=fn;}replaceChildren(){this.children=[];}append(...nodes){this.children.push(...nodes);}}
async function app(url=''){
 const elements=new Map(),store=new Map(),writes=[],get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
 const ctx=vm.createContext({console,URL,AbortSignal,Map,Set,Number,JSON,Error,localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},document:{getElementById:get,createElement:()=>new Element()},writes,fetch:async url=>({ok:true,json:async()=>({items:new URL(url).searchParams.get('action')==='collection'?[{id:'13',gameId:'13',name:'Catan'}]:[{id:'99',gameId:'13',name:'Catan',date:'2026-10-10',quantity:1,players:[]}],total:1})})});
 const main=new vm.SourceTextModule(await fs.readFile(new URL('../bgg-account.js',import.meta.url),'utf8'),{context:ctx});
 await main.link(async spec=>new vm.SourceTextModule(spec.includes('firebase-config')?`export const bggSearchUrl=${JSON.stringify(url)};`:`export const cloudConfigured=()=>true;export async function connectCloud(cb){globalThis.auth=cb;}export async function idToken(){return 'token';}export async function loadBggProfile(){return null;}export async function saveBggProfile(profile,uid){writes.push({profile,uid});}export async function loadBggData(){return {collection:[],plays:[]};}export async function saveBggData(kind,username,items,uid){writes.push({kind,username,items,uid});}`,{context:ctx}));await main.evaluate();return {get,store,writes,auth:ctx.auth};
}
test('registration is scoped to Google account and import is disabled before server connection',async()=>{const a=await app();assert.equal(a.get('bggAccountSection').hidden,true);await a.auth({uid:'one'});a.get('bggUsername').value='alice';await a.get('bggRegister').onclick();assert.equal(a.writes[0].profile.username,'alice');assert.equal(a.get('bggImport').disabled,true);await a.auth({uid:'two'});assert.equal(a.get('bggUsername').value,'');await a.auth(null);assert.equal(a.get('bggAccountSection').hidden,true);});
test('owned games and public plays are saved separately with stable IDs',async()=>{const a=await app('https://example.com/bgg');await a.auth({uid:'one'});a.get('bggUsername').value='alice';await a.get('bggRegister').onclick();await a.get('bggImport').onclick();assert.equal(a.writes[1].kind,'collection');assert.equal(a.writes[2].kind,'plays');assert.equal(a.writes[2].items[0].id,'99');assert.equal(a.get('bggAccountData').children[0].children[0].textContent,'보유 게임 · 1개');assert.equal(a.get('bggAccountData').children[1].children[0].textContent,'BGG 플레이 기록 · 1개');});
